#!/bin/bash

echo "════════════════════════════════════════════════════════════════"
echo "  COPIANDO FRONTEND PARA SERVIDOR - MeuMU Online"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Este script vai copiar todos os arquivos do frontend React"
echo "para o seu servidor VPS."
echo ""
echo "INSTRUÇÕES:"
echo ""
echo "1. Baixe TODOS os arquivos deste projeto para seu computador"
echo ""
echo "2. Copie via SCP/SFTP para o servidor:"
echo ""
echo "   scp -r ./* root@meumu.com:/home/meumu.com/public_html/frontend/"
echo ""
echo "   OU use um cliente FTP como FileZilla:"
echo "   - Host: meumu.com"
echo "   - User: root"
echo "   - Porta: 22 (SFTP)"
echo "   - Pasta remota: /home/meumu.com/public_html/frontend/"
echo ""
echo "3. Depois execute no servidor SSH:"
echo ""
echo "   cd /home/meumu.com/public_html/frontend"
echo "   npm install --legacy-peer-deps"
echo "   npm run build"
echo "   cp -r dist /home/meumu.com/public_html/backend-nodejs/"
echo "   cd /home/meumu.com/public_html/backend-nodejs"
echo "   pm2 restart meumu-backend"
echo ""
echo "4. Acesse: http://meumu.com:3001"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "OPÇÃO ALTERNATIVA - Via Git:"
echo ""
echo "1. No servidor, instale git:"
echo "   apt install git -y"
echo ""
echo "2. Clone este repositório:"
echo "   cd /home/meumu.com/public_html"
echo "   git clone [URL_DO_SEU_REPO] frontend"
echo ""
echo "3. Build e copie:"
echo "   cd frontend"
echo "   npm install --legacy-peer-deps"
echo "   npm run build"
echo "   cp -r dist ../backend-nodejs/"
echo "   cd ../backend-nodejs"
echo "   pm2 restart meumu-backend"
echo ""
echo "════════════════════════════════════════════════════════════════"
