<?php
/**
 * MeuMU Online - Executor de Comandos
 * 
 * @version 3.0.0
 * @author MeuMU Team
 * @copyright (c) 2024-2025 MeuMU Online, All Rights Reserved
 */

session_start();
define('access', true);
define('__ROOT_DIR__', str_replace('install/executor.php', '', str_replace('\\', '/', __FILE__)));

header('Content-Type: application/json');

// Verificar se está no processo de instalação
if(!isset($_SESSION['install_step'])) {
	echo json_encode(['success' => false, 'error' => 'Sessão de instalação não encontrada']);
	exit;
}

$command = $_POST['command'] ?? '';

switch($command) {
	case 'npm_install':
		npmInstall();
		break;
		
	case 'npm_build':
		npmBuild();
		break;
		
	case 'create_htaccess':
		createHtaccess();
		break;
		
	case 'verify_installation':
		verifyInstallation();
		break;
		
	default:
		echo json_encode(['success' => false, 'error' => 'Comando desconhecido']);
		break;
}

function npmInstall() {
	$rootDir = __ROOT_DIR__;
	$output = [];
	$returnCode = 0;
	
	// Verificar se node/npm estão disponíveis
	exec('which npm 2>&1', $checkOutput, $checkCode);
	if($checkCode !== 0) {
		echo json_encode([
			'success' => false,
			'error' => 'Node.js/npm não encontrado. Instale o Node.js primeiro: https://nodejs.org/',
			'output' => ''
		]);
		return;
	}
	
	// Executar npm install
	chdir($rootDir);
	exec('npm install 2>&1', $output, $returnCode);
	
	$outputText = implode("\n", $output);
	
	if($returnCode !== 0) {
		echo json_encode([
			'success' => false,
			'error' => 'Falha ao instalar dependências. Verifique as permissões e tente manualmente.',
			'output' => $outputText
		]);
		return;
	}
	
	echo json_encode([
		'success' => true,
		'message' => 'Dependências instaladas com sucesso!',
		'output' => $outputText
	]);
}

function npmBuild() {
	$rootDir = __ROOT_DIR__;
	$output = [];
	$returnCode = 0;
	
	// Executar npm run build
	chdir($rootDir);
	exec('npm run build 2>&1', $output, $returnCode);
	
	$outputText = implode("\n", $output);
	
	if($returnCode !== 0) {
		echo json_encode([
			'success' => false,
			'error' => 'Falha ao buildar React. Verifique os erros acima.',
			'output' => $outputText
		]);
		return;
	}
	
	// Verificar se a pasta /dist foi criada
	if(!is_dir($rootDir . 'dist')) {
		echo json_encode([
			'success' => false,
			'error' => 'Build executado mas a pasta /dist não foi criada!',
			'output' => $outputText
		]);
		return;
	}
	
	echo json_encode([
		'success' => true,
		'message' => 'React buildado com sucesso! Pasta /dist criada.',
		'output' => $outputText
	]);
}

function createHtaccess() {
	$rootDir = __ROOT_DIR__;
	$htaccessPath = $rootDir . 'dist/.htaccess';
	
	// Conteúdo do .htaccess
	$htaccessContent = <<<'HTACCESS'
# MeuMU Online - Apache Configuration
# Generated by installer v3.0.0

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /
	
	# Servir arquivos estáticos diretamente
	RewriteCond %{REQUEST_FILENAME} -f [OR]
	RewriteCond %{REQUEST_FILENAME} -d
	RewriteRule ^ - [L]
	
	# React Router - redirecionar tudo para index.html
	RewriteRule ^ index.html [L]
</IfModule>

# Segurança: Prevenir listagem de diretórios
Options -Indexes

# Habilitar compressão GZIP
<IfModule mod_deflate.c>
	AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
</IfModule>

# Cache de arquivos estáticos
<IfModule mod_expires.c>
	ExpiresActive On
	ExpiresByType image/jpg "access plus 1 year"
	ExpiresByType image/jpeg "access plus 1 year"
	ExpiresByType image/gif "access plus 1 year"
	ExpiresByType image/png "access plus 1 year"
	ExpiresByType image/svg+xml "access plus 1 year"
	ExpiresByType text/css "access plus 1 month"
	ExpiresByType application/javascript "access plus 1 month"
	ExpiresByType text/javascript "access plus 1 month"
</IfModule>

# Forçar HTTPS (opcional - descomente se tiver SSL)
# <IfModule mod_rewrite.c>
#     RewriteCond %{HTTPS} off
#     RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
# </IfModule>
HTACCESS;
	
	// Verificar se já existe
	if(file_exists($htaccessPath)) {
		// Fazer backup
		$backupPath = $htaccessPath . '.backup.' . time();
		copy($htaccessPath, $backupPath);
		$message = '.htaccess já existia - backup criado e arquivo sobrescrito';
	} else {
		$message = '.htaccess criado com sucesso!';
	}
	
	// Criar .htaccess
	if(file_put_contents($htaccessPath, $htaccessContent) === false) {
		echo json_encode([
			'success' => false,
			'error' => 'Erro ao criar .htaccess. Verifique permissões de escrita na pasta /dist'
		]);
		return;
	}
	
	// Verificar se mod_rewrite está habilitado
	$modRewriteEnabled = in_array('mod_rewrite', apache_get_modules());
	
	if(!$modRewriteEnabled) {
		$message .= ' AVISO: mod_rewrite pode não estar habilitado! Execute: sudo a2enmod rewrite';
	}
	
	echo json_encode([
		'success' => true,
		'message' => $message
	]);
}

function verifyInstallation() {
	$rootDir = __ROOT_DIR__;
	$errors = [];
	$warnings = [];
	
	// Verificar arquivos críticos
	if(!file_exists($rootDir . 'config.php')) {
		$errors[] = 'config.php não encontrado';
	}
	
	if(!file_exists($rootDir . 'backend-nodejs/.env')) {
		$errors[] = 'backend-nodejs/.env não encontrado';
	}
	
	if(!is_dir($rootDir . 'dist')) {
		$errors[] = 'Pasta /dist não encontrada';
	}
	
	if(!file_exists($rootDir . 'dist/index.html')) {
		$errors[] = 'dist/index.html não encontrado';
	}
	
	if(!is_dir($rootDir . 'dist/assets')) {
		$warnings[] = 'Pasta dist/assets não encontrada - build pode ter falhado';
	}
	
	if(!file_exists($rootDir . 'dist/.htaccess')) {
		$warnings[] = '.htaccess não encontrado em /dist';
	}
	
	// Verificar permissões
	if(!is_writable($rootDir . 'dist')) {
		$warnings[] = 'Pasta /dist sem permissão de escrita';
	}
	
	// Verificar node_modules
	if(!is_dir($rootDir . 'node_modules')) {
		$errors[] = 'Pasta node_modules não encontrada - npm install falhou?';
	}
	
	if(!is_dir($rootDir . 'backend-nodejs/node_modules')) {
		$warnings[] = 'Backend sem node_modules - lembre de executar: cd backend-nodejs && npm install';
	}
	
	// Resultado final
	if(count($errors) > 0) {
		echo json_encode([
			'success' => false,
			'error' => 'Verificação falhou: ' . implode(', ', $errors)
		]);
		return;
	}
	
	$message = 'Todos os arquivos verificados com sucesso!';
	if(count($warnings) > 0) {
		$message .= ' (Avisos: ' . implode(', ', $warnings) . ')';
	}
	
	echo json_encode([
		'success' => true,
		'message' => $message
	]);
}
?>
