<?php
/**
 * MeuMU Online - Step 6: Configuração Final (v2 - SEM EXECUÇÃO AUTOMÁTICA)
 * 
 * @version 2.0.1
 * @author MeuMU Team
 * @copyright (c) 2024-2025 MeuMU Online, All Rights Reserved
 */

if(!defined('access') or !access or access != 'install') die();

// Verificar dados
if(!isset($_SESSION['install_db_host'])) {
	echo '<div class="alert alert-danger"><span>❌</span><div>Dados de instalação não encontrados.</div></div>';
	exit;
}

// Processar instalação final
if(isset($_POST['install_final'])) {
	try {
		$siteUrl = trim($_POST['site_url'] ?? '');
		$backendMode = $_POST['backend_mode'] ?? 'pm2';
		
		if(empty($siteUrl)) {
			throw new Exception('Digite a URL do site.');
		}
		
		// Remover trailing slash
		$siteUrl = rtrim($siteUrl, '/');
		
		// Criar arquivo .env no backend
		$envContent = "# MeuMU Online - Backend Configuration\n";
		$envContent .= "# Generated by installer v2.0.1\n\n";
		
		$envContent .= "# Database MU (Read Only)\n";
		$envContent .= "DB_MU_HOST=" . $_SESSION['install_db_host'] . "\n";
		$envContent .= "DB_MU_PORT=" . $_SESSION['install_db_port'] . "\n";
		$envContent .= "DB_MU_NAME=" . $_SESSION['install_db_mu'] . "\n";
		$envContent .= "DB_MU_USER=" . $_SESSION['install_db_user'] . "\n";
		$envContent .= "DB_MU_PASSWORD=" . $_SESSION['install_db_pass'] . "\n\n";
		
		$envContent .= "# Database Web (Read + Write)\n";
		$envContent .= "DB_WEB_HOST=" . $_SESSION['install_db_host'] . "\n";
		$envContent .= "DB_WEB_PORT=" . $_SESSION['install_db_port'] . "\n";
		$envContent .= "DB_WEB_NAME=" . $_SESSION['install_db_web'] . "\n";
		$envContent .= "DB_WEB_USER=" . $_SESSION['install_db_user'] . "\n";
		$envContent .= "DB_WEB_PASSWORD=" . $_SESSION['install_db_pass'] . "\n\n";
		
		$envContent .= "# JWT Secret\n";
		$envContent .= "JWT_SECRET=" . bin2hex(random_bytes(32)) . "\n\n";
		
		$envContent .= "# Server\n";
		$envContent .= "PORT=3001\n";
		$envContent .= "NODE_ENV=production\n\n";
		
		$envContent .= "# CORS\n";
		$envContent .= "ALLOWED_ORIGINS={$siteUrl},http://localhost:5173\n";
		
		$envPath = __ROOT_DIR__ . 'backend-nodejs/.env';
		if(file_put_contents($envPath, $envContent) === false) {
			throw new Exception('Erro ao criar arquivo .env no backend.');
		}
		
		// Criar config.php na raiz
		$configContent = "<?php\n";
		$configContent .= "/**\n";
		$configContent .= " * MeuMU Online - Configuration\n";
		$configContent .= " * Generated by installer v2.0.1\n";
		$configContent .= " */\n\n";
		
		$configContent .= "// Database MU (Read Only)\n";
		$configContent .= "define('DB_MU_HOST', '" . $_SESSION['install_db_host'] . "');\n";
		$configContent .= "define('DB_MU_PORT', '" . $_SESSION['install_db_port'] . "');\n";
		$configContent .= "define('DB_MU_NAME', '" . $_SESSION['install_db_mu'] . "');\n";
		$configContent .= "define('DB_MU_USER', '" . $_SESSION['install_db_user'] . "');\n";
		$configContent .= "define('DB_MU_PASSWORD', '" . addslashes($_SESSION['install_db_pass']) . "');\n\n";
		
		$configContent .= "// Database Web (Read + Write)\n";
		$configContent .= "define('DB_WEB_HOST', '" . $_SESSION['install_db_host'] . "');\n";
		$configContent .= "define('DB_WEB_PORT', '" . $_SESSION['install_db_port'] . "');\n";
		$configContent .= "define('DB_WEB_NAME', '" . $_SESSION['install_db_web'] . "');\n";
		$configContent .= "define('DB_WEB_USER', '" . $_SESSION['install_db_user'] . "');\n";
		$configContent .= "define('DB_WEB_PASSWORD', '" . addslashes($_SESSION['install_db_pass']) . "');\n\n";
		
		$configContent .= "// Site\n";
		$configContent .= "define('SITE_URL', '{$siteUrl}');\n";
		$configContent .= "define('BACKEND_PORT', '3001');\n";
		$configContent .= "define('BACKEND_MODE', '{$backendMode}');\n";
		$configContent .= "define('INSTALLED', true);\n";
		$configContent .= "?>";
		
		$configPath = __ROOT_DIR__ . 'config.php';
		if(file_put_contents($configPath, $configContent) === false) {
			throw new Exception('Erro ao criar arquivo config.php');
		}
		
		// SUCESSO - NÃO TENTA EXECUTAR NADA!
		$_SESSION['install_final_success'] = true;
		$_SESSION['install_backend_started'] = false;
		$_SESSION['install_site_url'] = $siteUrl;
		$_SESSION['install_backend_mode'] = $backendMode;
		
	} catch (Exception $e) {
		$_SESSION['install_final_error'] = $e->getMessage();
	}
}

// Continuar para próximo step
if(isset($_POST['finish'])) {
	$_SESSION['install_step']++;
	header('Location: index.php');
	exit;
}

// Valores padrão
$siteUrl = $_SESSION['install_site_url'] ?? 'http://' . $_SERVER['HTTP_HOST'];
$backendMode = 'pm2';
?>

<h2>⚙️ Configuração Final</h2>
<p>Configure a URL do site. Os arquivos de configuração serão criados automaticamente.</p>

<br>

<div class="alert alert-info">
	<span>ℹ️</span>
	<div>
		<strong>O que este step faz:</strong>
		<ul style="margin-left: 20px; margin-top: 8px;">
			<li>✅ Cria o arquivo <code>.env</code> no backend</li>
			<li>✅ Cria o arquivo <code>config.php</code> na raiz</li>
			<li>❌ NÃO tenta instalar dependências npm</li>
			<li>❌ NÃO tenta iniciar o backend</li>
		</ul>
	</div>
</div>

<div class="alert alert-warning">
	<span>⚠️</span>
	<div>
		<strong>Após a instalação, você precisa:</strong>
		<br><br>
		<strong>1. Buildar o frontend React:</strong><br>
		<code>npm install && npm run build</code>
		<br><br>
		<strong>2. Iniciar o backend Node.js:</strong><br>
		<code>cd backend-nodejs && npm install && npm start</code>
		<br><br>
		<strong>3. Configurar servidor web para apontar para /dist</strong>
	</div>
</div>

<?php
// Mostrar erro
if(isset($_SESSION['install_final_error'])) {
	echo '<div class="alert alert-danger">';
	echo '<span>❌</span>';
	echo '<div><strong>Erro:</strong> ' . htmlspecialchars($_SESSION['install_final_error']) . '</div>';
	echo '</div>';
	unset($_SESSION['install_final_error']);
}

// Mostrar sucesso
if(isset($_SESSION['install_final_success'])) {
	$siteUrl = $_SESSION['install_site_url'];
	$backendMode = $_SESSION['install_backend_mode'];
	
	echo '<div class="alert alert-success">';
	echo '<span>✅</span>';
	echo '<div>';
	echo '<strong>Arquivos criados com sucesso!</strong><br>';
	echo '• Arquivo <code>.env</code> criado em <code>/backend-nodejs/.env</code><br>';
	echo '• Arquivo <code>config.php</code> criado na raiz<br>';
	echo '• URL do site: <strong>' . htmlspecialchars($siteUrl) . '</strong><br>';
	echo '• Modo backend: <strong>' . htmlspecialchars($backendMode) . '</strong>';
	echo '</div>';
	echo '</div>';
	
	echo '<div class="alert alert-warning">';
	echo '<span>📝</span>';
	echo '<div>';
	echo '<strong>PRÓXIMOS PASSOS OBRIGATÓRIOS:</strong><br><br>';
	echo '<strong>1. Buildar o Frontend:</strong><br>';
	echo '<code style="display:block;background:rgba(0,0,0,0.3);padding:8px;border-radius:4px;margin:8px 0;">npm install<br>npm run build</code>';
	echo '<strong>2. Iniciar o Backend:</strong><br>';
	echo '<code style="display:block;background:rgba(0,0,0,0.3);padding:8px;border-radius:4px;margin:8px 0;">cd backend-nodejs<br>npm install<br>npm start</code>';
	echo '<strong>3. Configurar Servidor Web:</strong><br>';
	echo 'Apache: DocumentRoot apontar para <code>/dist</code><br>';
	echo 'Nginx: root apontar para <code>/dist</code>';
	echo '</div>';
	echo '</div>';
	
	echo '<form method="post">';
	echo '<div class="btn-group">';
	echo '<button type="submit" name="finish" class="btn btn-success btn-lg">🎉 Finalizar Instalação</button>';
	echo '</div>';
	echo '</form>';
	
	unset($_SESSION['install_final_success']);
	
} else {
	// Formulário
	?>
	
	<form method="post">
		<div class="form-group">
			<label class="form-label">URL do Site *</label>
			<input type="text" name="site_url" class="form-control" value="<?php echo htmlspecialchars($siteUrl); ?>" required placeholder="http://meumu.com">
			<small class="form-help">URL completa do seu site (sem barra no final)</small>
		</div>
		
		<div class="form-group">
			<label class="form-label">Modo de Execução do Backend:</label>
			<small class="form-help" style="display:block;margin-bottom:12px;">Você vai iniciar manualmente, mas escolha qual método vai usar:</small>
			
			<label style="display: block; padding: 16px; background: rgba(255,255,255,0.05); border: 2px solid rgba(255,184,0,0.3); border-radius: 8px; cursor: pointer; margin-bottom: 12px;">
				<input type="radio" name="backend_mode" value="pm2" checked style="margin-right: 8px;">
				<strong>PM2 (Recomendado)</strong>
				<br>
				<small style="color: rgba(255,255,255,0.6); display: block; margin-top: 4px; margin-left: 24px;">
					Gerenciador de processos. Reinicia automaticamente. Comando: <code>pm2 start src/server.js --name meumu-backend</code>
				</small>
			</label>
			
			<label style="display: block; padding: 16px; background: rgba(255,255,255,0.05); border: 2px solid rgba(255,255,255,0.1); border-radius: 8px; cursor: pointer;">
				<input type="radio" name="backend_mode" value="standalone" style="margin-right: 8px;">
				<strong>Node Standalone</strong>
				<br>
				<small style="color: rgba(255,255,255,0.6); display: block; margin-top: 4px; margin-left: 24px;">
					Execução simples. Para testes. Comando: <code>npm start</code>
				</small>
			</label>
		</div>
		
		<div class="btn-group">
			<button type="submit" name="install_final" class="btn btn-primary btn-lg">
				💾 Criar Arquivos de Configuração
			</button>
		</div>
	</form>
	
	<?php
}
?>
