<?php
/**
 * MeuMU Online - Step 6: Configuração Final
 * 
 * @version 2.0.0
 * @author MeuMU Team
 * @copyright (c) 2024-2025 MeuMU Online, All Rights Reserved
 */

if(!defined('access') or !access or access != 'install') die();

// Verificar dados
if(!isset($_SESSION['install_db_host'])) {
	echo '<div class="alert alert-danger"><span>❌</span><div>Dados de instalação não encontrados.</div></div>';
	exit;
}

// Processar instalação final
if(isset($_POST['install_final'])) {
	try {
		$siteUrl = trim($_POST['site_url'] ?? '');
		$backendMode = $_POST['backend_mode'] ?? 'pm2';
		
		if(empty($siteUrl)) {
			throw new Exception('Digite a URL do site.');
		}
		
		// Remover trailing slash
		$siteUrl = rtrim($siteUrl, '/');
		
		// Criar arquivo .env no backend
		$envContent = "# MeuMU Online - Backend Configuration\n";
		$envContent .= "# Generated by installer v2.0.0\n\n";
		
		$envContent .= "# Database MU (Read Only)\n";
		$envContent .= "DB_MU_HOST=" . $_SESSION['install_db_host'] . "\n";
		$envContent .= "DB_MU_PORT=" . $_SESSION['install_db_port'] . "\n";
		$envContent .= "DB_MU_NAME=" . $_SESSION['install_db_mu'] . "\n";
		$envContent .= "DB_MU_USER=" . $_SESSION['install_db_user'] . "\n";
		$envContent .= "DB_MU_PASSWORD=" . $_SESSION['install_db_pass'] . "\n\n";
		
		$envContent .= "# Database Web (Read + Write)\n";
		$envContent .= "DB_WEB_HOST=" . $_SESSION['install_db_host'] . "\n";
		$envContent .= "DB_WEB_PORT=" . $_SESSION['install_db_port'] . "\n";
		$envContent .= "DB_WEB_NAME=" . $_SESSION['install_db_web'] . "\n";
		$envContent .= "DB_WEB_USER=" . $_SESSION['install_db_user'] . "\n";
		$envContent .= "DB_WEB_PASSWORD=" . $_SESSION['install_db_pass'] . "\n\n";
		
		$envContent .= "# JWT Secret\n";
		$envContent .= "JWT_SECRET=" . bin2hex(random_bytes(32)) . "\n\n";
		
		$envContent .= "# Server\n";
		$envContent .= "PORT=3001\n";
		$envContent .= "NODE_ENV=production\n\n";
		
		$envContent .= "# CORS\n";
		$envContent .= "ALLOWED_ORIGINS={$siteUrl},http://localhost:5173\n";
		
		$envPath = __ROOT_DIR__ . 'backend-nodejs/.env';
		if(file_put_contents($envPath, $envContent) === false) {
			throw new Exception('Erro ao criar arquivo .env no backend.');
		}
		
		// Criar config.php na raiz
		$configContent = "<?php\n";
		$configContent .= "/**\n";
		$configContent .= " * MeuMU Online - Configuration\n";
		$configContent .= " * Generated by installer v2.0.0\n";
		$configContent .= " */\n\n";
		
		$configContent .= "// Database MU (Read Only)\n";
		$configContent .= "define('DB_MU_HOST', '" . $_SESSION['install_db_host'] . "');\n";
		$configContent .= "define('DB_MU_PORT', '" . $_SESSION['install_db_port'] . "');\n";
		$configContent .= "define('DB_MU_NAME', '" . $_SESSION['install_db_mu'] . "');\n";
		$configContent .= "define('DB_MU_USER', '" . $_SESSION['install_db_user'] . "');\n";
		$configContent .= "define('DB_MU_PASSWORD', '" . addslashes($_SESSION['install_db_pass']) . "');\n\n";
		
		$configContent .= "// Database Web (Read + Write)\n";
		$configContent .= "define('DB_WEB_HOST', '" . $_SESSION['install_db_host'] . "');\n";
		$configContent .= "define('DB_WEB_PORT', '" . $_SESSION['install_db_port'] . "');\n";
		$configContent .= "define('DB_WEB_NAME', '" . $_SESSION['install_db_web'] . "');\n";
		$configContent .= "define('DB_WEB_USER', '" . $_SESSION['install_db_user'] . "');\n";
		$configContent .= "define('DB_WEB_PASSWORD', '" . addslashes($_SESSION['install_db_pass']) . "');\n\n";
		
		$configContent .= "// Site\n";
		$configContent .= "define('SITE_URL', '{$siteUrl}');\n";
		$configContent .= "define('BACKEND_PORT', '3001');\n";
		$configContent .= "define('BACKEND_MODE', '{$backendMode}');\n";
		$configContent .= "define('INSTALLED', true);\n";
		$configContent .= "?>";
		
		$configPath = __ROOT_DIR__ . 'config.php';
		if(file_put_contents($configPath, $configContent) === false) {
			throw new Exception('Erro ao criar arquivo config.php');
		}
		
		// Tentar iniciar backend
		$backendPath = __ROOT_DIR__ . 'backend-nodejs';
		$backendStarted = false;
		$backendError = null;
		
		// REMOVIDO: Tentativa automática de npm install e pm2
		// O usuário deve iniciar o backend manualmente
		$backendError = 'Backend não iniciado automaticamente. Execute manualmente: cd backend-nodejs && npm install && npm start';
		
		$_SESSION['install_final_success'] = true;
		$_SESSION['install_backend_started'] = false;
		$_SESSION['install_backend_error'] = $backendError;
		$_SESSION['install_site_url'] = $siteUrl;
		
	} catch (Exception $e) {
		$_SESSION['install_final_error'] = $e->getMessage();
	}
}

// Continuar para próximo step
if(isset($_POST['finish'])) {
	$_SESSION['install_step']++;
	header('Location: index.php');
	exit;
}

// Valores padrão
$siteUrl = $_SESSION['install_site_url'] ?? 'http://' . $_SERVER['HTTP_HOST'];
$backendMode = 'pm2';
?>

<h2>⚙️ Configuração Final</h2>
<p>Última etapa! Configure a URL do site e o modo de execução do backend.</p>

<br>

<div class="alert alert-warning">
	<span>⚠️</span>
	<div>
		<strong>Importante:</strong><br>
		O instalador irá criar os arquivos de configuração (<code>.env</code> e <code>config.php</code>), mas o backend Node.js precisa ser iniciado MANUALMENTE após a instalação.
		<br><br>
		<strong>Comandos para iniciar o backend:</strong><br>
		<code>cd backend-nodejs && npm install && npm start</code>
	</div>
</div>

<?php
// Mostrar erro
if(isset($_SESSION['install_final_error'])) {
	echo '<div class="alert alert-danger">';
	echo '<span>❌</span>';
	echo '<div>' . $_SESSION['install_final_error'] . '</div>';
	echo '</div>';
	unset($_SESSION['install_final_error']);
}

// Mostrar sucesso
if(isset($_SESSION['install_final_success'])) {
	$backendStarted = $_SESSION['install_backend_started'];
	$backendError = $_SESSION['install_backend_error'];
	$siteUrl = $_SESSION['install_site_url'];
	
	echo '<div class="alert alert-success">';
	echo '<span>✅</span>';
	echo '<div>';
	echo '<strong>Arquivos criados com sucesso!</strong><br>';
	echo '• Arquivo <code>.env</code> criado no backend<br>';
	echo '• Arquivo <code>config.php</code> criado na raiz<br>';
	if($backendStarted) {
		echo '• Backend Node.js iniciado com sucesso';
	} else {
		echo '• Backend não iniciou automaticamente (ver abaixo)';
	}
	echo '</div>';
	echo '</div>';
	
	if($backendError) {
		echo '<div class="alert alert-warning">';
		echo '<span>⚠️</span>';
		echo '<div>';
		echo '<strong>Backend não iniciou automaticamente:</strong><br>';
		echo $backendError . '<br><br>';
		echo '<strong>Inicie manualmente:</strong><br>';
		echo '<code>cd backend-nodejs && npm install && npm start</code>';
		echo '</div>';
		echo '</div>';
	}
	
	echo '<form method="post">';
	echo '<div class="btn-group">';
	echo '<button type="submit" name="finish" class="btn btn-success btn-lg">🎉 Finalizar Instalação</button>';
	echo '</div>';
	echo '</form>';
	
	unset($_SESSION['install_final_success']);
	unset($_SESSION['install_backend_started']);
	unset($_SESSION['install_backend_error']);
	
} else {
	// Formulário
	?>
	
	<form method="post">
		<div class="form-group">
			<label class="form-label">URL do Site</label>
			<input type="text" name="site_url" class="form-control" value="<?php echo htmlspecialchars($siteUrl); ?>" required>
			<small class="form-help">URL completa do seu site (ex: http://seudominio.com ou http://localhost)</small>
		</div>
		
		<div class="form-group">
			<label class="form-label">Modo de Execução do Backend:</label>
			<br><br>
			
			<label style="display: block; padding: 16px; background: rgba(255,255,255,0.05); border: 2px solid rgba(255,184,0,0.3); border-radius: 8px; cursor: pointer; margin-bottom: 12px;">
				<input type="radio" name="backend_mode" value="pm2" checked style="margin-right: 8px;">
				<strong>PM2 (Recomendado)</strong>
				<br>
				<small style="color: rgba(255,255,255,0.6); display: block; margin-top: 4px; margin-left: 24px;">
					Gerenciador de processos Node.js. Reinicia automaticamente em caso de erro. Ideal para produção.
				</small>
			</label>
			
			<label style="display: block; padding: 16px; background: rgba(255,255,255,0.05); border: 2px solid rgba(255,255,255,0.1); border-radius: 8px; cursor: pointer;">
				<input type="radio" name="backend_mode" value="standalone" style="margin-right: 8px;">
				<strong>Node Standalone</strong>
				<br>
				<small style="color: rgba(255,255,255,0.6); display: block; margin-top: 4px; margin-left: 24px;">
					Execução simples do Node.js. Para testes locais. Não reinicia automaticamente.
				</small>
			</label>
		</div>
		
		<div class="btn-group">
			<button type="submit" name="install_final" class="btn btn-primary btn-lg">
				🚀 Instalar e Configurar
			</button>
		</div>
	</form>
	
	<?php
}
?>