<?php
/**
 * MeuMU Online - Step 6: Instalação Automática
 * 
 * @version 3.0.0 - AUTOMÁTICO COM PROGRESSO VISUAL
 * @author MeuMU Team
 * @copyright (c) 2024-2025 MeuMU Online, All Rights Reserved
 */

if(!defined('access') or !access or access != 'install') die();

// Verificar dados
if(!isset($_SESSION['install_db_host'])) {
	echo '<div class="alert alert-danger"><span>❌</span><div>Dados de instalação não encontrados.</div></div>';
	exit;
}

// Processar configuração
if(isset($_POST['create_config'])) {
	try {
		$siteUrl = trim($_POST['site_url'] ?? '');
		
		if(empty($siteUrl)) {
			throw new Exception('Digite a URL do site.');
		}
		
		// Remover trailing slash
		$siteUrl = rtrim($siteUrl, '/');
		
		// Criar arquivo .env no backend
		$envContent = "# MeuMU Online - Backend Configuration\n";
		$envContent .= "# Generated by installer v3.0.0\n\n";
		
		$envContent .= "# Database MU (Read Only)\n";
		$envContent .= "DB_MU_HOST=" . $_SESSION['install_db_host'] . "\n";
		$envContent .= "DB_MU_PORT=" . $_SESSION['install_db_port'] . "\n";
		$envContent .= "DB_MU_NAME=" . $_SESSION['install_db_mu'] . "\n";
		$envContent .= "DB_MU_USER=" . $_SESSION['install_db_user'] . "\n";
		$envContent .= "DB_MU_PASSWORD=" . $_SESSION['install_db_pass'] . "\n\n";
		
		$envContent .= "# Database Web (Read + Write)\n";
		$envContent .= "DB_WEB_HOST=" . $_SESSION['install_db_host'] . "\n";
		$envContent .= "DB_WEB_PORT=" . $_SESSION['install_db_port'] . "\n";
		$envContent .= "DB_WEB_NAME=" . $_SESSION['install_db_web'] . "\n";
		$envContent .= "DB_WEB_USER=" . $_SESSION['install_db_user'] . "\n";
		$envContent .= "DB_WEB_PASSWORD=" . $_SESSION['install_db_pass'] . "\n\n";
		
		$envContent .= "# JWT Secret\n";
		$envContent .= "JWT_SECRET=" . bin2hex(random_bytes(32)) . "\n\n";
		
		$envContent .= "# Server\n";
		$envContent .= "PORT=3001\n";
		$envContent .= "NODE_ENV=production\n\n";
		
		$envContent .= "# CORS\n";
		$envContent .= "ALLOWED_ORIGINS={$siteUrl},http://localhost:5173\n";
		
		$envPath = __ROOT_DIR__ . 'backend-nodejs/.env';
		if(file_put_contents($envPath, $envContent) === false) {
			throw new Exception('Erro ao criar arquivo .env no backend.');
		}
		
		// Criar config.php na raiz
		$configContent = "<?php\n";
		$configContent .= "/**\n";
		$configContent .= " * MeuMU Online - Configuration\n";
		$configContent .= " * Generated by installer v3.0.0\n";
		$configContent .= " */\n\n";
		
		$configContent .= "// Database MU (Read Only)\n";
		$configContent .= "define('DB_MU_HOST', '" . $_SESSION['install_db_host'] . "');\n";
		$configContent .= "define('DB_MU_PORT', '" . $_SESSION['install_db_port'] . "');\n";
		$configContent .= "define('DB_MU_NAME', '" . $_SESSION['install_db_mu'] . "');\n";
		$configContent .= "define('DB_MU_USER', '" . $_SESSION['install_db_user'] . "');\n";
		$configContent .= "define('DB_MU_PASSWORD', '" . addslashes($_SESSION['install_db_pass']) . "');\n\n";
		
		$configContent .= "// Database Web (Read + Write)\n";
		$configContent .= "define('DB_WEB_HOST', '" . $_SESSION['install_db_host'] . "');\n";
		$configContent .= "define('DB_WEB_PORT', '" . $_SESSION['install_db_port'] . "');\n";
		$configContent .= "define('DB_WEB_NAME', '" . $_SESSION['install_db_web'] . "');\n";
		$configContent .= "define('DB_WEB_USER', '" . $_SESSION['install_db_user'] . "');\n";
		$configContent .= "define('DB_WEB_PASSWORD', '" . addslashes($_SESSION['install_db_pass']) . "');\n\n";
		
		$configContent .= "// Site\n";
		$configContent .= "define('SITE_URL', '{$siteUrl}');\n";
		$configContent .= "define('BACKEND_PORT', '3001');\n";
		$configContent .= "define('INSTALLED', true);\n";
		$configContent .= "?>";
		
		$configPath = __ROOT_DIR__ . 'config.php';
		if(file_put_contents($configPath, $configContent) === false) {
			throw new Exception('Erro ao criar arquivo config.php');
		}
		
		$_SESSION['install_config_created'] = true;
		$_SESSION['install_site_url'] = $siteUrl;
		
		echo json_encode(['success' => true]);
		exit;
		
	} catch (Exception $e) {
		echo json_encode(['success' => false, 'error' => $e->getMessage()]);
		exit;
	}
}

// Valores padrão
$siteUrl = $_SESSION['install_site_url'] ?? 'http://' . $_SERVER['HTTP_HOST'];
$rootDir = __ROOT_DIR__;
?>

<style>
.progress-container {
	margin: 24px 0;
}

.progress-step {
	background: rgba(255,255,255,0.05);
	border: 2px solid rgba(255,255,255,0.1);
	border-radius: 8px;
	padding: 20px;
	margin-bottom: 16px;
	position: relative;
	overflow: hidden;
}

.progress-step.active {
	border-color: #FFB800;
	background: rgba(255,184,0,0.1);
}

.progress-step.success {
	border-color: #28a745;
	background: rgba(40,167,69,0.1);
}

.progress-step.error {
	border-color: #dc3545;
	background: rgba(220,53,69,0.1);
}

.progress-step-header {
	display: flex;
	align-items: center;
	margin-bottom: 12px;
}

.progress-step-icon {
	width: 40px;
	height: 40px;
	border-radius: 50%;
	display: flex;
	align-items: center;
	justify-content: center;
	font-size: 20px;
	margin-right: 16px;
	background: rgba(255,255,255,0.1);
}

.progress-step.active .progress-step-icon {
	background: #FFB800;
	color: #000;
	animation: pulse 1.5s infinite;
}

.progress-step.success .progress-step-icon {
	background: #28a745;
	color: #fff;
}

.progress-step.error .progress-step-icon {
	background: #dc3545;
	color: #fff;
}

@keyframes pulse {
	0%, 100% { transform: scale(1); }
	50% { transform: scale(1.1); }
}

.progress-step-title {
	font-size: 18px;
	font-weight: bold;
	color: #fff;
}

.progress-step-status {
	font-size: 14px;
	color: rgba(255,255,255,0.7);
	margin-top: 4px;
}

.progress-bar {
	width: 100%;
	height: 8px;
	background: rgba(0,0,0,0.3);
	border-radius: 4px;
	overflow: hidden;
	margin-top: 12px;
}

.progress-bar-fill {
	height: 100%;
	background: linear-gradient(90deg, #FFB800, #FFC800);
	border-radius: 4px;
	transition: width 0.3s ease;
	width: 0%;
}

.progress-step.success .progress-bar-fill {
	background: linear-gradient(90deg, #28a745, #3abf5e);
	width: 100%;
}

.progress-step.error .progress-bar-fill {
	background: linear-gradient(90deg, #dc3545, #e74c3c);
}

.progress-output {
	background: #0a0a0a;
	border: 1px solid rgba(255,184,0,0.3);
	border-radius: 4px;
	padding: 12px;
	margin-top: 12px;
	font-family: 'Courier New', monospace;
	font-size: 12px;
	color: #28a745;
	max-height: 200px;
	overflow-y: auto;
	display: none;
}

.progress-output.visible {
	display: block;
}

.progress-output-line {
	margin: 2px 0;
}

.spinner {
	border: 3px solid rgba(255,255,255,0.1);
	border-top: 3px solid #FFB800;
	border-radius: 50%;
	width: 20px;
	height: 20px;
	animation: spin 1s linear infinite;
	display: inline-block;
	margin-left: 8px;
}

@keyframes spin {
	0% { transform: rotate(0deg); }
	100% { transform: rotate(360deg); }
}

.hidden {
	display: none;
}
</style>

<h2>🚀 Instalação Automática</h2>
<p>O instalador vai configurar tudo automaticamente com progresso visual em tempo real!</p>

<br>

<div class="alert alert-info">
	<span>ℹ️</span>
	<div>
		<strong>O que será feito automaticamente:</strong>
		<ul style="margin-left: 20px; margin-top: 8px;">
			<li>✅ Criar arquivos de configuração (.env e config.php)</li>
			<li>✅ Instalar dependências do frontend (npm install)</li>
			<li>✅ Buildar React para produção (npm run build)</li>
			<li>✅ Configurar .htaccess com Rewrite Rules</li>
			<li>✅ Verificar permissões e estrutura de pastas</li>
		</ul>
		<br>
		<strong>Tempo estimado:</strong> 2-5 minutos (depende da velocidade do servidor)
	</div>
</div>

<br>

<!-- Formulário Inicial -->
<div id="config-form">
	<form id="form-config">
		<div class="form-group">
			<label class="form-label">URL do Site *</label>
			<input type="text" id="site_url" name="site_url" class="form-control" value="<?php echo htmlspecialchars($siteUrl); ?>" required placeholder="http://meumu.com">
			<small class="form-help">URL completa do seu site (sem barra no final)</small>
		</div>
		
		<div class="form-group">
			<label class="form-label">Caminho Raiz do Projeto:</label>
			<input type="text" id="root_dir" name="root_dir" class="form-control" value="<?php echo htmlspecialchars($rootDir); ?>" readonly>
			<small class="form-help">Detectado automaticamente</small>
		</div>
		
		<div class="btn-group">
			<button type="submit" class="btn btn-primary btn-lg">
				🚀 Iniciar Instalação Automática
			</button>
		</div>
	</form>
</div>

<!-- Container de Progresso -->
<div id="progress-container" class="progress-container hidden">
	
	<!-- Step 1: Criar Configurações -->
	<div class="progress-step" id="step-config" data-step="1">
		<div class="progress-step-header">
			<div class="progress-step-icon">1</div>
			<div>
				<div class="progress-step-title">Criar Arquivos de Configuração</div>
				<div class="progress-step-status">Aguardando...</div>
			</div>
		</div>
		<div class="progress-bar">
			<div class="progress-bar-fill"></div>
		</div>
	</div>
	
	<!-- Step 2: npm install -->
	<div class="progress-step" id="step-npm-install" data-step="2">
		<div class="progress-step-header">
			<div class="progress-step-icon">2</div>
			<div>
				<div class="progress-step-title">Instalar Dependências (npm install)</div>
				<div class="progress-step-status">Aguardando...</div>
			</div>
		</div>
		<div class="progress-bar">
			<div class="progress-bar-fill"></div>
		</div>
		<div class="progress-output" id="output-npm-install"></div>
	</div>
	
	<!-- Step 3: npm run build -->
	<div class="progress-step" id="step-npm-build" data-step="3">
		<div class="progress-step-header">
			<div class="progress-step-icon">3</div>
			<div>
				<div class="progress-step-title">Buildar React (npm run build)</div>
				<div class="progress-step-status">Aguardando...</div>
			</div>
		</div>
		<div class="progress-bar">
			<div class="progress-bar-fill"></div>
		</div>
		<div class="progress-output" id="output-npm-build"></div>
	</div>
	
	<!-- Step 4: Criar .htaccess -->
	<div class="progress-step" id="step-htaccess" data-step="4">
		<div class="progress-step-header">
			<div class="progress-step-icon">4</div>
			<div>
				<div class="progress-step-title">Configurar .htaccess</div>
				<div class="progress-step-status">Aguardando...</div>
			</div>
		</div>
		<div class="progress-bar">
			<div class="progress-bar-fill"></div>
		</div>
	</div>
	
	<!-- Step 5: Verificar -->
	<div class="progress-step" id="step-verify" data-step="5">
		<div class="progress-step-header">
			<div class="progress-step-icon">5</div>
			<div>
				<div class="progress-step-title">Verificar Instalação</div>
				<div class="progress-step-status">Aguardando...</div>
			</div>
		</div>
		<div class="progress-bar">
			<div class="progress-bar-fill"></div>
		</div>
	</div>
	
</div>

<!-- Resultado Final -->
<div id="final-result" class="hidden"></div>

<script>
document.getElementById('form-config').addEventListener('submit', async (e) => {
	e.preventDefault();
	
	// Esconder formulário e mostrar progresso
	document.getElementById('config-form').classList.add('hidden');
	document.getElementById('progress-container').classList.remove('hidden');
	
	const siteUrl = document.getElementById('site_url').value;
	const rootDir = document.getElementById('root_dir').value;
	
	try {
		// STEP 1: Criar configurações
		await runStep('config', 'Criando arquivos de configuração...', async () => {
			const formData = new FormData();
			formData.append('create_config', '1');
			formData.append('site_url', siteUrl);
			
			const response = await fetch('index.php', {
				method: 'POST',
				body: formData
			});
			
			const result = await response.json();
			if (!result.success) {
				throw new Error(result.error || 'Erro ao criar configurações');
			}
			
			return 'Arquivos .env e config.php criados!';
		});
		
		// STEP 2: npm install
		await runStep('npm-install', 'Instalando dependências do frontend...', async () => {
			return await execCommand('npm_install', 'output-npm-install');
		});
		
		// STEP 3: npm run build
		await runStep('npm-build', 'Buildando React para produção...', async () => {
			return await execCommand('npm_build', 'output-npm-build');
		});
		
		// STEP 4: Criar .htaccess
		await runStep('htaccess', 'Configurando .htaccess...', async () => {
			return await execCommand('create_htaccess');
		});
		
		// STEP 5: Verificar
		await runStep('verify', 'Verificando instalação...', async () => {
			return await execCommand('verify_installation');
		});
		
		// SUCESSO TOTAL!
		showFinalSuccess();
		
	} catch (error) {
		showFinalError(error.message);
	}
});

async function runStep(stepId, statusText, asyncFunc) {
	const step = document.getElementById(`step-${stepId}`);
	const statusEl = step.querySelector('.progress-step-status');
	const progressBar = step.querySelector('.progress-bar-fill');
	
	// Ativar step
	step.classList.add('active');
	statusEl.textContent = statusText;
	
	// Animar progresso
	progressBar.style.width = '50%';
	
	try {
		const result = await asyncFunc();
		
		// Sucesso
		step.classList.remove('active');
		step.classList.add('success');
		statusEl.textContent = '✅ ' + result;
		progressBar.style.width = '100%';
		
		// Trocar ícone para check
		step.querySelector('.progress-step-icon').textContent = '✓';
		
	} catch (error) {
		// Erro
		step.classList.remove('active');
		step.classList.add('error');
		statusEl.textContent = '❌ ' + error.message;
		
		// Trocar ícone para X
		step.querySelector('.progress-step-icon').textContent = '✗';
		
		throw error;
	}
}

async function execCommand(command, outputId = null) {
	const response = await fetch('executor.php', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
		},
		body: `command=${command}`
	});
	
	const result = await response.json();
	
	if (outputId && result.output) {
		const outputEl = document.getElementById(outputId);
		outputEl.classList.add('visible');
		outputEl.innerHTML = result.output.split('\n').map(line => 
			`<div class="progress-output-line">${escapeHtml(line)}</div>`
		).join('');
	}
	
	if (!result.success) {
		throw new Error(result.error || 'Erro ao executar comando');
	}
	
	return result.message;
}

function escapeHtml(text) {
	const div = document.createElement('div');
	div.textContent = text;
	return div.innerHTML;
}

function showFinalSuccess() {
	document.getElementById('final-result').innerHTML = `
		<div class="alert alert-success" style="margin-top: 32px;">
			<span style="font-size: 32px;">🎉</span>
			<div>
				<strong style="font-size: 20px;">INSTALAÇÃO CONCLUÍDA COM SUCESSO!</strong>
				<br><br>
				<strong>Próximos passos:</strong>
				<ol style="margin-left: 20px; margin-top: 12px;">
					<li><strong>Reiniciar Apache:</strong> <code>sudo systemctl restart apache2</code> ou <code>sudo service apache2 restart</code></li>
					<li><strong>Iniciar Backend:</strong> <code>cd backend-nodejs && npm start</code></li>
					<li><strong>Acessar site:</strong> <a href="<?php echo $siteUrl; ?>" target="_blank"><?php echo $siteUrl; ?></a></li>
					<li><strong>DELETAR pasta /install</strong> por segurança!</li>
				</ol>
			</div>
		</div>
		
		<div class="btn-group" style="margin-top: 24px;">
			<a href="../" class="btn btn-success btn-lg">🎮 Ir para o Site</a>
		</div>
	`;
	document.getElementById('final-result').classList.remove('hidden');
}

function showFinalError(errorMessage) {
	document.getElementById('final-result').innerHTML = `
		<div class="alert alert-danger" style="margin-top: 32px;">
			<span>❌</span>
			<div>
				<strong>Erro durante a instalação:</strong>
				<br><br>
				${escapeHtml(errorMessage)}
				<br><br>
				<strong>Soluções possíveis:</strong>
				<ul style="margin-left: 20px; margin-top: 8px;">
					<li>Verifique as permissões da pasta: <code>chmod -R 755 <?php echo $rootDir; ?></code></li>
					<li>Verifique se o Node.js está instalado: <code>node --version</code></li>
					<li>Execute manualmente: <code>npm install && npm run build</code></li>
					<li>Verifique os logs de erro acima para mais detalhes</li>
				</ul>
			</div>
		</div>
		
		<div class="btn-group" style="margin-top: 24px;">
			<button onclick="location.reload()" class="btn btn-primary">🔄 Tentar Novamente</button>
		</div>
	`;
	document.getElementById('final-result').classList.remove('hidden');
}
</script>
